### ISSUE TITLE
Was PicassoOnScrollListener removed?

### ISSUE THREAD

**Issue by miquelbeltran** [eyeem/RecyclerViewTools#19]
Hello, the PicassoOnScrollListener was removed in the latest version of the library.

Any reason why it was removed?

Thanks for the good work!

**Comment by ronaldoeyeem** [comment]
hi @miquelbeltran ,

yes, the whole `:extras` got removed.
The original idea was to put there stuff that would be depending on 3rd party libraries (such as picasso), to avoid adding 3rd party libraries to other developers projects.

But at the end the whole `:extras` was just that one class, and event thou it works as advertised, it's a very simple class that doesn't really add value to the library.

So yeah, during the migration to being able to use it on `jcenter()` without importing any other repo we clear up all the `extras`.

If you want that class I suggest two possible approaches:
1. use the older version of the library (no suggested, there're some fancy new features and a couple of fixes that you might want to use)
2. The code is not lost forever, it's all in the git commit history, so just copy the class from [this link](https://github.com/eyeem/RecyclerViewTools/blob/481743e0cdd8168485b413b78d0794248edea32c/extras/src/main/java/com/eyeem/recyclerviewtools/extras/PicassoOnScrollListener.java) into your project and keep using the latest version of the lib.

**Comment by miquelbeltran** [comment]
Hi Ronaldo, thanks for the reply!

I ended up copying it as you suggest.
