### ISSUE TITLE
useing  sections does not work

### ISSUE THREAD

**Issue by luckyjmcc** [eyeem/RecyclerViewTools#21]
useing  sections does not work

**Comment by luckyjmcc** [comment]
i mean sticky section

**Comment by ronaldoeyeem** [comment]
@iloveaman this library does not have "sticky section", you're very welcome to code it and submit a PullRequest.

This library have normal sections (that are just another view on the RecyclerView child views). A working implementation of it can be seen on our app (https://play.google.com/store/apps/details?id=com.baseapp.eyeem) on the `Settings` page.
