### ISSUE TITLE
Gradle?

### ISSUE THREAD

**Issue by brockoli** [eyeem/RecyclerViewTools#3]
How can I add this project to my gradle config?

**Comment by ronaldoeyeem** [comment]
@brockoli I didn't upload this yet to maven. But it's good you reminded me to do it.
I'll later today update to the latest version and upload it.

**Not**e: on the latest versions of the code (local on my machine) all the functionalities that overlap with Googles coordinator layout (https://developer.android.com/reference/android/support/design/widget/CoordinatorLayout.html) have been removed. There's no more reason for them.

**Comment by brockoli** [comment]
That would help me out a lot.  Also easier to reference back to your project.  Credit where credit's due.

**Comment by brockoli** [comment]
Did you get a chance to get this up on Maven Central yet?

**Comment by ronaldoeyeem** [comment]
@brockoli just uploaded to Maven as a snapshot. Check the pull request and the readme

``` Java
repositories {
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

dependencies {
    compile 'com.eyeem.recyclerviewtools:library:0.0.1-SNAPSHOT@aar'
    compile 'com.eyeem.recyclerviewtools:library-extras:0.0.1-SNAPSHOT@aar'
}
```
