### ISSUE TITLE
Picasso on scroll listener not working 

### ISSUE THREAD

**Issue by branemk** [eyeem/RecyclerViewTools#7]
Do I need to configure anything more than 

private static final Object PICASSO_TAG = new Object(); 
and
recycler.addOnScrollListener(new PicassoOnScrollListener(PICASSO_TAG)); for picasso to stop loading images on scroll  ? 

I just want to use picasso functionality , I saw your simple but for some reason its not working for me.

**Comment by ronaldoeyeem** [comment]
the PicassoScrollListener is a super super simple class, check it out:
https://github.com/eyeem/RecyclerViewTools/blob/master/extras/src/main/java/com/eyeem/recyclerviewtools/extras/PicassoOnScrollListener.java

and I can't imagine why it wouldn't be working.
Are you tagging your Picasso calls with the same tag from the listener??? For example:
`Picasso.with(context).load(url).tag(PICASSO_TAG).into(imageView)` ???

**Comment by branemk** [comment]
Yes I saw that class , my error was not using tag() in picasso call.
Now I am using                      Picasso.with(holder.imageView.getContext()).load(data.get(position).image).tag("PICASSO_TAG").placeholder(R.drawable.grey).priority(Picasso.Priority.HIGH).config(Bitmap.Config.RGB_565).resize(640,360).into(holder.imageView,PicassoPalette.with((data.get(position).image), holder.imageView).use(PicassoPalette.Profile.VIBRANT).intoTextColor(holder.textView,PicassoPalette.Swatch.RGB));

and in my fragment recycleList.addOnScrollListener(new PicassoOnScrollListener("PICASSO_TAG"));

 Seems that everything is working fine,thank you .
